[package]
name = "whitewater"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
