kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: whitewater-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.33.0
    extraPortMappings:
      - containerPort: 30090
        hostPort: 8090
        protocol: TCP
